AttributeError
Python 3.7.3: /Users/yiqiang/.conda/envs/ZzClient/bin/python
Thu Nov  5 20:02:52 2020

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 /Users/yiqiang/Work/Workplace/Python/ZzClient/ZzClient/view/test1page.py in on_pushButton_clicked(self=<test1page.Test1Page object>)
   23         theme = LocalStorage.themeGet()
   24         if theme == 'dark':
   25             self.theme.toggle('light')
   26         else:
   27             self.theme.toggle('dark')
self = <test1page.Test1Page object>
self.theme = <ZzClient.config.theme.Theme object>
self.theme.toggle = <bound method Theme.toggle of <class 'ZzClient.config.theme.Theme'>>

 /Users/yiqiang/Work/Workplace/Python/ZzClient/ZzClient/config/theme.py in toggle(cls=<class 'ZzClient.config.theme.Theme'>, theme='light')
   76         skin_rc = 'ZzClient.resource.qss.theme.{theme}.skin_rc'.format(theme=current_theme)
   77         style_rc = 'ZzClient.resource.qss.theme.{theme}.style_rc'.format(theme=current_theme)
   78         skin_rc.qCleanupResources()
   79         style_rc.qCleanupResources()
   80         # 1).改变主题
skin_rc = 'ZzClient.resource.qss.theme.dark.skin_rc'
skin_rc.qCleanupResources undefined
AttributeError: 'str' object has no attribute 'qCleanupResources'
    __cause__ = None
    __class__ = <class 'AttributeError'>
    __context__ = None
    __delattr__ = <method-wrapper '__delattr__' of AttributeError object>
    __dict__ = {}
    __dir__ = <built-in method __dir__ of AttributeError object>
    __doc__ = 'Attribute not found.'
    __eq__ = <method-wrapper '__eq__' of AttributeError object>
    __format__ = <built-in method __format__ of AttributeError object>
    __ge__ = <method-wrapper '__ge__' of AttributeError object>
    __getattribute__ = <method-wrapper '__getattribute__' of AttributeError object>
    __gt__ = <method-wrapper '__gt__' of AttributeError object>
    __hash__ = <method-wrapper '__hash__' of AttributeError object>
    __init__ = <method-wrapper '__init__' of AttributeError object>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of AttributeError object>
    __lt__ = <method-wrapper '__lt__' of AttributeError object>
    __ne__ = <method-wrapper '__ne__' of AttributeError object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of AttributeError object>
    __reduce_ex__ = <built-in method __reduce_ex__ of AttributeError object>
    __repr__ = <method-wrapper '__repr__' of AttributeError object>
    __setattr__ = <method-wrapper '__setattr__' of AttributeError object>
    __setstate__ = <built-in method __setstate__ of AttributeError object>
    __sizeof__ = <built-in method __sizeof__ of AttributeError object>
    __str__ = <method-wrapper '__str__' of AttributeError object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    args = ("'str' object has no attribute 'qCleanupResources'",)
    with_traceback = <built-in method with_traceback of AttributeError object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "/Users/yiqiang/Work/Workplace/Python/ZzClient/ZzClient/view/test1page.py", line 25, in on_pushButton_clicked
    self.theme.toggle('light')
  File "/Users/yiqiang/Work/Workplace/Python/ZzClient/ZzClient/config/theme.py", line 78, in toggle
    skin_rc.qCleanupResources()
AttributeError: 'str' object has no attribute 'qCleanupResources'

