AttributeError
Python 3.7.3: /Users/yiqiang/.conda/envs/ZzClient/bin/python
Sun Nov 29 12:48:30 2020

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 /Users/yiqiang/Work/Workplace/Python/ZzClient/ZzClient/widget/activity/modal/action_sheet.py in <lambda>()
   43         if not hasattr(self, 'drawer'):
   44             self.drawer = Drawer(self.parent, stretch=0.9, direction=Drawer.BOTTOM, popup=False)
   45             self.dialog.on_drop.connect(lambda: self.drawer.hideSef())
   46             self.drawer.setWidget(self.dialog)
   47         self.drawer.show()
self = <widget.activity.modal.action_sheet.ActionSheet object>
self.dialog = <widget.activity.modal.action_sheet.PopupContainer object>
self.dialog.on_drop = <bound PYQT_SIGNAL on_drop of PopupContainer object>
self.dialog.on_drop.connect = <built-in method connect of PyQt5.QtCore.pyqtBoundSignal object>
self.drawer = <widget.activity.drawer.Drawer object>
self.drawer.hideSef undefined
AttributeError: 'Drawer' object has no attribute 'hideSef'
    __cause__ = None
    __class__ = <class 'AttributeError'>
    __context__ = None
    __delattr__ = <method-wrapper '__delattr__' of AttributeError object>
    __dict__ = {}
    __dir__ = <built-in method __dir__ of AttributeError object>
    __doc__ = 'Attribute not found.'
    __eq__ = <method-wrapper '__eq__' of AttributeError object>
    __format__ = <built-in method __format__ of AttributeError object>
    __ge__ = <method-wrapper '__ge__' of AttributeError object>
    __getattribute__ = <method-wrapper '__getattribute__' of AttributeError object>
    __gt__ = <method-wrapper '__gt__' of AttributeError object>
    __hash__ = <method-wrapper '__hash__' of AttributeError object>
    __init__ = <method-wrapper '__init__' of AttributeError object>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of AttributeError object>
    __lt__ = <method-wrapper '__lt__' of AttributeError object>
    __ne__ = <method-wrapper '__ne__' of AttributeError object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of AttributeError object>
    __reduce_ex__ = <built-in method __reduce_ex__ of AttributeError object>
    __repr__ = <method-wrapper '__repr__' of AttributeError object>
    __setattr__ = <method-wrapper '__setattr__' of AttributeError object>
    __setstate__ = <built-in method __setstate__ of AttributeError object>
    __sizeof__ = <built-in method __sizeof__ of AttributeError object>
    __str__ = <method-wrapper '__str__' of AttributeError object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    args = ("'Drawer' object has no attribute 'hideSef'",)
    with_traceback = <built-in method with_traceback of AttributeError object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "/Users/yiqiang/Work/Workplace/Python/ZzClient/ZzClient/widget/activity/modal/action_sheet.py", line 45, in <lambda>
    self.dialog.on_drop.connect(lambda: self.drawer.hideSef())
AttributeError: 'Drawer' object has no attribute 'hideSef'

